### PR TITLE
Adds exports to kt_jvm_import to enable bazel-deps support.

### PR DESCRIPTION
**Pull request by pbsf**
This pull request is a copy from the one in https://github.com/bazelbuild/rules_kotlin/pull/151 by @wcurrie.

### CODE REVIEW

**Comment by cgruber** [comment]
I'm willing to do this, but I"m not sure how build-deps is supposed to distinguish what libraries are kotlin and what libraries are java, in order to decide whether to use a kt_jvm_import.  In http://github.com/square/bazel_maven_repository, I ended up just reimplementing the equivalent of a no-ijar import for use by that library, so it wouldn't have to know particular details about the jar artifact being downloaded.  It might be wiser to take that approach.

That said, it's not unreasonable to add this feature, even if I'd use a different mechanism if I were in your shoes.  It's a totally valid gap in the import's feature set, so I'll review this and merge it.

**Comment by cgruber** [comment]
Leaving this comment to try to trigger buildkite.

**Comment by pbsf** [comment]
bazel-deps entries have a mandatory `lang` field. This is how we let bazel-deps know whether a dependency is a kotlin, java, or scala one:
```
  io.mockk:
    mockk:
      version: 1.9.3
      lang: kotlin
  io.netty:
    netty-all:
      version: 4.1.17.Final
      lang: java
  com.thesamet.scalapb:
    scalapb-json4s:
      version: 0.7.1
      lang: scala
```

I'll make sure to study your approach, but bazel-deps has been working fine for us at Acqio.

**Comment by cgruber** [comment]
SGTM.

**Review by cgruber — APPROVED** [review]

**Comment by cgruber** [comment]
Trigger CLA

**Comment by cgruber** [comment]
Awesome.  Please sign the CLA, and I'm happy to merge this. 

I'll try to roll a release in the next day or so.

**Pull request merged**
