### PR TITLE
Fix jdeps building

### PR DESCRIPTION
**Pull request by szinn**
.jdeps files were not being created correctly such that IntelliJ could correctly identify the external libraries.

### CODE REVIEW

**Comment by cgruber** [comment]
Holy crap, @inez and I were just talking about this today.  I'll definitely review this tomorrow and ty to get it incorporated in a release post-haste.

**Comment by cgruber** [comment]
Oh wait... this should be redone to target the bazelbuild/rules_kotlin, not this repo, since that's the main one, and I don't want to add features/fixes here that ought to be upstream.

**Comment by szinn** [comment]
Submitted the PR to bazelbuild/rules_kotlin.

**Comment by cgruber** [comment]
Closing this, as it was added to the upstream project, and then pulled in.

**Pull request closed without merging**
